require 'erb'

class PodWriter

  def initialize tree
    @tree = tree
  end

  def write path
    Dir.mkdir(path) if !File.directory?(path)
    config = @tree.config
    @tree.each_module do | m |
      fn = path + '/' + m.name + '.pod'
      File.unlink(fn) if File.exist?(fn)
      fullname = "Biolib::"+m.name
      brief_descr = ""
      detailed_descr = ""
      m.each_description do | descr |
        doxyxml = DoxyTransform.new(descr.brief)
        brief_descr += doxyxml.to_s + "\n\n"
        doxyxml = DoxyTransform.new(descr.detailed)
        detailed_descr += doxyxml.to_s + "\n\n"
      end
      File.open(fn,"w") do | f |

        header_template = ERB.new <<-EOF
# <%= fn %>

%perlcode %{
@EXPORT_OK = qw/
        <% m.each_mapped_func do |func| %> <%= func.name %> 
        <% end %>
             /;
%EXPORT_TAGS = ( all => [ @EXPORT_OK ] );

__END__

=head1 NAME

<%= fullname %> - <%= brief_descr.strip %>

=head1 SYNOPSIS

<%= detailed_descr.strip %>

    use <%= fullname %> qw /:all/;


EOF
        f.print header_template.result(binding)
        f.print "\n\nTextual output generated by "
        f.print config.copyright_msg,"\n"
      end
    end
  end
end
