biolib_affyio.c
CELOBJECT* open_celfile(const char *celfilename)
Open a cel file using the Affyio library and return a pointer to a CELOBJECT, which maintains state keeping track of the opened CEL data. The full array data gets stored in memory - including stddev, npixels, masks and outliers.Use the direct celfile_methods instead, for more effecient memory usage. celfilename points to a valid Affy CEL file (or .gz edition) pointer to CELOBJECT close_celfile cel_intensities cel_stddev celfile_intensities open_cdffile
References CELOBJECT::cel, CELOBJECT::id.
void close_celfile(CELOBJECT *object)
Close a CELOBJECT opened with open_celfile and frees up RAM object
References CELOBJECT::masks, CELOBJECT::outliers.
unsigned long cel_num_cols(CELOBJECT *object)
number of columns on the chip
unsigned long cel_num_rows(CELOBJECT *object)
number of rows on the chip
Referenced by cel_intensity_xy.
unsigned long cel_num_masks(CELOBJECT *object)
number of masked probes
unsigned long cel_num_outliers(CELOBJECT *object)
number of outliers
unsigned long cel_size(CELOBJECT *object)
number of cells (probes) - [INTENSITY]->NumberCells (rows*cols)
unsigned long cel_num_intensities(CELOBJECT *object)
number of intensities (probes)
double cel_intensity(CELOBJECT *object, unsigned long index)
index of cel/probe an intensity value cel_pm
double cel_intensity_xy(CELOBJECT *object, unsigned long x, unsigned long y)
x pos on chip y pos on chip an intensity value cel_pm
References cel_num_rows.
Referenced by cel_mm, cel_pm.
double* cel_intensities(CELOBJECT *object)
a double array to the cel/probe intensities cel_pm
double cel_stddev(CELOBJECT *object, unsigned long index)
the stddev for the cel/probe
double* cel_stddevs(CELOBJECT *object)
a double array to the stddev
unsigned int cel_mask(CELOBJECT *object, unsigned long index)
index is the nth item in the mask list the cel/probe mask index cel_num_masks
References CELOBJECT::masks.
unsigned int cel_outlier(CELOBJECT *object, unsigned long index)
index is the nth item in the outlier list the outlier cel/probe index cel_num_outliers
References CELOBJECT::outliers.
static void cdf_alloc_probesets(CDFOBJECT *cdfobject)
static void cdf_calc_text_probe_refs(CDFOBJECT *cdfobject)
CDFOBJECT* open_cdffile(const char *cdffilename)
Open a cdf file using the Affyio library and return a pointer to a CDFOBJECT, which maintains state keeping track of the opened CDF data. Unlike the Affyio internal representation the Biolib affyio CDF methods represent a unified layout for Affymetrix chips. Basically every probeset can return the name, probe values (PM, MM) and QC. Loading all other information is trivial, as Affyio makes it available - but not implemented here, at this point.FIXME: XDA format not tested cdffilename points to a valid Affy CDF file (textual or XDA binary) pointer to CDFOBJECT close_cdffile
References CDFOBJECT::cols, CDFOBJECT::id, CDFOBJECT::isText, CDFOBJECT::rows, CDFOBJECT::text, CDFOBJECT::xda.
void close_cdffile(CDFOBJECT *cdfobject)
unsigned long cdf_num_probesets(CDFOBJECT *cdfobject)
number of probesets (units*blocks) including QC units
References CDFOBJECT::isText, CDFOBJECT::text, CDFOBJECT::xda.
CDFPROBESET* cdf_probeset_info(CDFOBJECT *cdfobject, unsigned int probeset)
CDFPROBESET related to probeset number
References CDFOBJECT::probeset.
CDFPROBE* cdf_pmprobe_info(CDFOBJECT *cdfobject, unsigned int probeset, unsigned int probe)
CDFPROBE related to probe in probeset
References CDFPROBESET::pm, CDFOBJECT::probeset.
CDFPROBE* cdf_mmprobe_info(CDFOBJECT *cdfobject, unsigned int probeset, unsigned int probe)
CDFPROBE related to probe in probeset
References CDFPROBESET::mm, CDFOBJECT::probeset.
double cel_pm(CELOBJECT *celobject, CDFOBJECT *cdfobject, unsigned int probeset, unsigned int probe)
FIXME: in progress... PM value (perfect match) of the probe number in probeset; -1 on error
References cel_intensity_xy, CDFPROBESET::pm, CDFOBJECT::probeset, CDFPROBE::x, CDFPROBE::y.
double cel_mm(CELOBJECT *celobject, CDFOBJECT *cdfobject, unsigned int probeset, unsigned int probe)
MM value (mismatch) of the probe number in probeset; -1 on error
References cel_intensity_xy, CDFPROBESET::mm, CDFOBJECT::probeset, CDFPROBE::x, CDFPROBE::y.